### ISSUE TITLE
Git tags for releases

### ISSUE THREAD

**Issue by erictapen** [kl/sub-batch#1]
Thanks for this nice application. I [started packaging it for Nixpkgs](https://github.com/NixOS/nixpkgs/pull/108951).

Could you add git tags for your releases? That makes it easier to maintain the package.

**Comment by kl** [comment]
Thanks for making a Nix package! :+1:  I've added a tag now for version 0.3.0. Let me know if there's anything else that needs to be fixed.

**Comment by erictapen** [comment]
Thanks!
