### ISSUE TITLE
Update Cargo.lock and release new version?

### ISSUE THREAD

**Issue by erictapen** [kl/sub-batch#2]
At Nixpkgs we recently started [scanning our packaged applications](https://github.com/NixOS/nixpkgs/issues/141368) for vulnerabilities reported in the advisory-db. It also reported four vulnerable packages for sub-batch. Three of these are fixed by just updating the `Cargo.lock` file with `cargo update`, the last one `image` is buried pretty deeply in the dependency tree and most likely doesn't affect the security of sub-batch. The build seems to run fine for me but I didn't test it any further.

Could you maybe update the package and create a new release?

**Comment by kl** [comment]
Thanks for the heads up, I have released a new version with the latest dependencies!

**Comment by erictapen** [comment]
Thank you very much. Could you also add a git tag vor 0.4.1? We don't follow crate releases, but try to use git tags wherever possible.

**Comment by kl** [comment]
Ah, I forgot to push the tag :). Done now
